
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author w1558955
 */
public class timeeeee extends javax.swing.JFrame {

    /**
     * Creates new form timeeeee
     */
    public timeeeee() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        digitValue = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        showDigit = new javax.swing.JButton();
        AddOne = new javax.swing.JButton();
        oneSecsDisplay = new javax.swing.JButton();
        oneSecs = new javax.swing.JTextField();
        showOneSecs = new javax.swing.JButton();
        tenSecs = new javax.swing.JTextField();
        showMins = new javax.swing.JButton();
        minutes = new javax.swing.JTextField();
        startTimer = new javax.swing.JButton();
        jTextField9 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        showOneMins = new javax.swing.JButton();
        tenMins = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        sec1 = new javax.swing.JTextField();
        showHours = new javax.swing.JButton();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        hours = new javax.swing.JTextField();
        showOneHours = new javax.swing.JButton();
        tenHours = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTextField16 = new javax.swing.JTextField();
        End = new javax.swing.JButton();
        stop = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        hour1 = new javax.swing.JTextField();
        min1 = new javax.swing.JTextField();
        tenhour1 = new javax.swing.JTextField();
        tenmin1 = new javax.swing.JTextField();
        tensec1 = new javax.swing.JTextField();
        Stoptimer = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        digitValue.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        digitValue.setText("000");
        digitValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                digitValueActionPerformed(evt);
            }
        });
        getContentPane().add(digitValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 90, 80, -1));

        jTextField1.setBackground(new java.awt.Color(153, 0, 0));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 120, 80, -1));

        jTextField2.setBackground(new java.awt.Color(153, 0, 0));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 140, 20, 70));

        jTextField3.setBackground(new java.awt.Color(153, 0, 0));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 140, 20, 70));

        jTextField4.setBackground(new java.awt.Color(153, 0, 0));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 210, 80, -1));

        jTextField5.setBackground(new java.awt.Color(153, 0, 0));
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 230, 20, 70));

        jTextField6.setBackground(new java.awt.Color(153, 0, 0));
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 230, 20, 70));

        jTextField7.setBackground(new java.awt.Color(153, 0, 0));
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 300, 80, -1));

        showDigit.setText("Show The Digit");
        showDigit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showDigitActionPerformed(evt);
            }
        });
        getContentPane().add(showDigit, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 60, -1, -1));

        AddOne.setText("Add One");
        AddOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddOneActionPerformed(evt);
            }
        });
        getContentPane().add(AddOne, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 330, -1, -1));

        oneSecsDisplay.setText("sec");
        oneSecsDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneSecsDisplayActionPerformed(evt);
            }
        });
        getContentPane().add(oneSecsDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 50, 140, 180));

        oneSecs.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        oneSecs.setText("0");
        oneSecs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneSecsActionPerformed(evt);
            }
        });
        getContentPane().add(oneSecs, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 240, 130, -1));

        showOneSecs.setText("tensSec");
        showOneSecs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showOneSecsActionPerformed(evt);
            }
        });
        getContentPane().add(showOneSecs, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 50, 140, 180));

        tenSecs.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tenSecs.setText("0");
        tenSecs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tenSecsActionPerformed(evt);
            }
        });
        getContentPane().add(tenSecs, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 240, 140, -1));

        showMins.setText("mins");
        showMins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showMinsActionPerformed(evt);
            }
        });
        getContentPane().add(showMins, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, 140, 180));

        minutes.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        minutes.setText("0");
        getContentPane().add(minutes, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 240, 140, -1));

        startTimer.setText("Start");
        startTimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startTimerActionPerformed(evt);
            }
        });
        getContentPane().add(startTimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 310, 100, 30));

        jTextField9.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 90, 10, -1));

        jLabel1.setText("Seconds");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 350, 120, -1));

        jLabel3.setText("Minutes");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 350, 70, 20));

        showOneMins.setText("tensMin");
        getContentPane().add(showOneMins, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 140, 180));

        tenMins.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tenMins.setText("0");
        getContentPane().add(tenMins, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, 140, -1));

        jLabel4.setText("Hours");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 350, 120, -1));

        sec1.setText("0");
        sec1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sec1ActionPerformed(evt);
            }
        });
        getContentPane().add(sec1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 370, 30, -1));

        showHours.setText("hours");
        showHours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showHoursActionPerformed(evt);
            }
        });
        getContentPane().add(showHours, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 140, 180));

        jTextField11.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 10, -1));

        jTextField12.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 10, -1));

        hours.setText("0");
        getContentPane().add(hours, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 140, -1));

        showOneHours.setText("tensHour");
        showOneHours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showOneHoursActionPerformed(evt);
            }
        });
        getContentPane().add(showOneHours, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 140, 180));

        tenHours.setText("0");
        getContentPane().add(tenHours, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 140, -1));

        jButton1.setText("Start Time");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 90, 40));

        jTextField16.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 170, 10, -1));

        End.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        End.setText("X");
        End.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EndActionPerformed(evt);
            }
        });
        getContentPane().add(End, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 0, 50, 40));

        stop.setText("Stop");
        stop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopActionPerformed(evt);
            }
        });
        getContentPane().add(stop, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 350, 100, 30));

        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        getContentPane().add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 390, 100, 30));

        jLabel6.setText("Hours");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 120, -1));

        jLabel7.setText("Minutes");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 264, 70, 20));

        jLabel2.setText("Seconds");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 270, 120, -1));

        hour1.setText("0");
        hour1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hour1ActionPerformed(evt);
            }
        });
        getContentPane().add(hour1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 370, 30, -1));

        min1.setText("0");
        min1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                min1ActionPerformed(evt);
            }
        });
        getContentPane().add(min1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 370, 30, -1));

        tenhour1.setText("0");
        tenhour1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tenhour1ActionPerformed(evt);
            }
        });
        getContentPane().add(tenhour1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 370, 30, -1));

        tenmin1.setText("0");
        tenmin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tenmin1ActionPerformed(evt);
            }
        });
        getContentPane().add(tenmin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 370, 30, -1));

        tensec1.setText("0");
        tensec1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tensec1ActionPerformed(evt);
            }
        });
        getContentPane().add(tensec1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 370, 30, -1));

        Stoptimer.setText("Stop Timer");
        Stoptimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StoptimerActionPerformed(evt);
            }
        });
        getContentPane().add(Stoptimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 400, -1, 40));

        jLabel5.setText("Please Enter Number ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 330, 120, -1));

        jLabel8.setText("Click Stop Timer");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 410, 80, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void digitValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_digitValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_digitValueActionPerformed

    private void showDigitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showDigitActionPerformed
        int digit1 = Integer.parseInt(digitValue.getText());
        if (digit1 == 0) {
            jTextField1.setVisible(true);
            jTextField2.setVisible(true);
            jTextField3.setVisible(true);
            jTextField4.setVisible(false);
            jTextField5.setVisible(true);
            jTextField6.setVisible(true);
            jTextField7.setVisible(true);
        }
        if (digit1 == 2) {
            jTextField1.setVisible(true);
            jTextField2.setVisible(true);
            jTextField3.setVisible(false);
            jTextField4.setVisible(true);
            jTextField5.setVisible(false);
            jTextField6.setVisible(true);
            jTextField7.setVisible(true);
        }

        if (digit1 == 3) {
            jTextField1.setVisible(true);
            jTextField2.setVisible(true);
            jTextField3.setVisible(false);
            jTextField4.setVisible(true);
            jTextField5.setVisible(true);
            jTextField6.setVisible(false);
            jTextField7.setVisible(true);
        }
        if (digit1 == 4) {
            jTextField1.setVisible(false);
            jTextField2.setVisible(true);
            jTextField3.setVisible(true);
            jTextField4.setVisible(true);
            jTextField5.setVisible(true);
            jTextField6.setVisible(false);
            jTextField7.setVisible(false);
        }

        if (digit1 == 5) {
            jTextField1.setVisible(true);
            jTextField2.setVisible(false);
            jTextField3.setVisible(true);
            jTextField4.setVisible(true);
            jTextField5.setVisible(true);
            jTextField6.setVisible(false);
            jTextField7.setVisible(true);
        }

        if (digit1 == 6) {
            jTextField1.setVisible(true);
            jTextField2.setVisible(false);
            jTextField3.setVisible(true);
            jTextField4.setVisible(true);
            jTextField5.setVisible(true);
            jTextField6.setVisible(true);
            jTextField7.setVisible(true);
        }

        if (digit1 == 7) {
            jTextField1.setVisible(true);
            jTextField2.setVisible(true);
            jTextField3.setVisible(false);
            jTextField4.setVisible(false);
            jTextField5.setVisible(true);
            jTextField6.setVisible(false);
            jTextField7.setVisible(false);
        }

        if (digit1 == 8) {
            jTextField1.setVisible(true);
            jTextField2.setVisible(true);
            jTextField3.setVisible(true);
            jTextField4.setVisible(true);
            jTextField5.setVisible(true);
            jTextField6.setVisible(true);
            jTextField7.setVisible(true);
        }

        if (digit1 == 9) {
            jTextField1.setVisible(true);
            jTextField2.setVisible(true);
            jTextField3.setVisible(true);
            jTextField4.setVisible(true);
            jTextField5.setVisible(true);
            jTextField6.setVisible(false);
            jTextField7.setVisible(true);
        }

        if (digit1 == 1){
            jTextField1.setVisible(false);
            jTextField2.setVisible(true);
            jTextField3.setVisible(false);
            jTextField4.setVisible(false);
            jTextField5.setVisible(true);
            jTextField6.setVisible(false);
            jTextField7.setVisible(false);
        }
    }//GEN-LAST:event_showDigitActionPerformed

    private void AddOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddOneActionPerformed
        int dd = Integer.parseInt(digitValue.getText());
        int secs = Integer.parseInt(oneSecs.getText());
        int ten = Integer.parseInt(tenSecs.getText());
        int min = Integer.parseInt(minutes.getText());
        int tensmins = Integer.parseInt(tenMins.getText());
        int hour = Integer.parseInt(hours.getText());
        int tenshours = Integer.parseInt(tenHours.getText());

        
        //seconds
        dd = dd + 1;

        if (dd == 10) {
            dd = 0;
            secs = secs + 1 ;
        }
        if (secs == 0) {
            oneSecsDisplay.setIcon(new  javax.swing.ImageIcon( "H:\\0.png"));
        }
        if (secs == 1) {
            oneSecsDisplay.setIcon(new  javax.swing.ImageIcon( "H:\\1.png"));
        }
        if (secs == 2) {
            oneSecsDisplay.setIcon(new  javax.swing.ImageIcon( "H:\\2.png"));
        }
        if (secs == 3) {
            oneSecsDisplay.setIcon(new  javax.swing.ImageIcon( "H:\\3.png"));
        }
        if (secs == 4) {
            oneSecsDisplay.setIcon(new  javax.swing.ImageIcon( "H:\\4.png"));
        }
        if (secs == 5) {
            oneSecsDisplay.setIcon(new  javax.swing.ImageIcon( "H:\\5.png"));
        }
        if (secs == 6) {
            oneSecsDisplay.setIcon(new  javax.swing.ImageIcon( "H:\\6.png"));
        }
        if (secs == 7) {
            oneSecsDisplay.setIcon(new  javax.swing.ImageIcon( "H:\\7.png"));
        }
        if (secs == 8) {
            oneSecsDisplay.setIcon(new  javax.swing.ImageIcon( "H:\\8.png"));
        }
        if (secs == 9) {
            oneSecsDisplay.setIcon(new  javax.swing.ImageIcon( "H:\\9.png"));
        }
        
        //tenth seconds
        
        if (secs == 10){
            secs = 0;
            ten = ten + 1;
        }
        if (ten == 0) {
            showOneSecs.setIcon(new  javax.swing.ImageIcon( "H:\\0.png"));
        }
        if (ten == 1) {
            showOneSecs.setIcon(new  javax.swing.ImageIcon( "H:\\1.png"));
        }
        if (ten == 2) {
            showOneSecs.setIcon(new  javax.swing.ImageIcon( "H:\\2.png"));
        }
        if (ten == 3) {
            showOneSecs.setIcon(new  javax.swing.ImageIcon( "H:\\3.png"));
        }
        if (ten == 4) {
            showOneSecs.setIcon(new  javax.swing.ImageIcon( "H:\\4.png"));
        }
        if (ten == 5) {
            showOneSecs.setIcon(new  javax.swing.ImageIcon( "H:\\5.png"));
        }
        if (ten == 6) {
            showOneSecs.setIcon(new  javax.swing.ImageIcon( "H:\\6.png"));
        }
        if (ten == 7) {
            showOneSecs.setIcon(new  javax.swing.ImageIcon( "H:\\7.png"));
        }
        if (ten == 8) {
            showOneSecs.setIcon(new  javax.swing.ImageIcon( "H:\\8.png"));
        }
        if (ten == 9) {
            showOneSecs.setIcon(new  javax.swing.ImageIcon( "H:\\9.png"));

        }

        //minutes 
        if (ten == 6){
            ten = 0;
            min = min + 1;
        }
        if (min == 0) {
            showMins.setIcon(new  javax.swing.ImageIcon( "H:\\0.png"));
        }
        if (min == 1) {
            showMins.setIcon(new  javax.swing.ImageIcon( "H:\\1.png"));
        }
        if (min == 2) {
            showMins.setIcon(new  javax.swing.ImageIcon( "H:\\2.png"));
        }
        if (min == 3) {
            showMins.setIcon(new  javax.swing.ImageIcon( "H:\\3.png"));
        }
        if (min == 4) {
            showMins.setIcon(new  javax.swing.ImageIcon( "H:\\4.png"));
        }
        if (min == 5) {
            showMins.setIcon(new  javax.swing.ImageIcon( "H:\\5.png"));
        }
        if (min == 6) {
            showMins.setIcon(new  javax.swing.ImageIcon( "H:\\6.png"));
        }
        if (min == 7) {
            showMins.setIcon(new  javax.swing.ImageIcon( "H:\\7.png"));
        }
        if (min == 8) {
            showMins.setIcon(new  javax.swing.ImageIcon( "H:\\8.png"));
        }
        if (min == 9) {
            showMins.setIcon(new  javax.swing.ImageIcon( "H:\\9.png"));
        }

        //tenth minutes
        
        if (min == 10){
            min = 0;
            tensmins = tensmins + 1;
        }
        if (tensmins == 0) {
            showOneMins.setIcon(new  javax.swing.ImageIcon( "H:\\0.png"));
        }
        if (tensmins == 1) {
            showOneMins.setIcon(new  javax.swing.ImageIcon( "H:\\1.png"));
        }
        if (tensmins == 2) {
            showOneMins.setIcon(new  javax.swing.ImageIcon( "H:\\2.png"));
        }
        if (tensmins == 3) {
            showOneMins.setIcon(new  javax.swing.ImageIcon( "H:\\3.png"));
        }
        if (tensmins == 4) {
            showOneMins.setIcon(new  javax.swing.ImageIcon( "H:\\4.png"));
        }
        if (tensmins == 5) {
            showOneMins.setIcon(new  javax.swing.ImageIcon( "H:\\5.png"));
        }
        if (tensmins == 6) {
            showOneMins.setIcon(new  javax.swing.ImageIcon( "H:\\6.png"));
        }
        if (tensmins == 7) {
            showOneMins.setIcon(new  javax.swing.ImageIcon( "H:\\7.png"));
        }
        if (tensmins == 8) {
            showOneMins.setIcon(new  javax.swing.ImageIcon( "H:\\8.png"));
        }
        if (tensmins == 9) {
            showOneMins.setIcon(new  javax.swing.ImageIcon( "H:\\9.png"));
        }

        //hours
        
        if (tensmins == 6) {
            tensmins = 0;
            hour = hour + 1;
        }

        if (hour == 0) {
            showHours.setIcon(new  javax.swing.ImageIcon( "H:\\0.png"));
        }
        if (hour == 1) {
            showHours.setIcon(new  javax.swing.ImageIcon( "H:\\1.png"));
        }
        if (hour == 2) {
            showHours.setIcon(new  javax.swing.ImageIcon( "H:\\2.png"));
        }
        if (hour == 3) {
            showHours.setIcon(new  javax.swing.ImageIcon( "H:\\3.png"));
        }
        if (hour == 4) {
            showHours.setIcon(new  javax.swing.ImageIcon( "H:\\4.png"));
        }
        if (hour == 5) {
            showHours.setIcon(new  javax.swing.ImageIcon( "H:\\5.png"));
        }
        if (hour == 6) {
            showHours.setIcon(new  javax.swing.ImageIcon( "H:\\6.png"));
        }
        if (hour == 7) {
            showHours.setIcon(new  javax.swing.ImageIcon( "H:\\7.png"));
        }
        if (hour == 8) {
            showHours.setIcon(new  javax.swing.ImageIcon( "H:\\8.png"));
        }
        if (hour == 9) {
            showHours.setIcon(new  javax.swing.ImageIcon( "H:\\9.png"));
        }

        //tenth hours
        
        if (hour == 10){
            hour = 0;
            tenshours = tenshours + 1;

        }
        if (tenshours == 0) {
            showOneHours.setIcon(new  javax.swing.ImageIcon( "H:\\0.png"));
        }
        if (tenshours == 1) {
            showOneHours.setIcon(new  javax.swing.ImageIcon( "H:\\1.png"));
        }
        if (tenshours == 2) {
            showOneHours.setIcon(new  javax.swing.ImageIcon( "H:\\2.png"));
        }
        if (tenshours == 3) {
            showOneHours.setIcon(new  javax.swing.ImageIcon( "H:\\3.png"));
        }
        if (tenshours == 4) {
            showOneHours.setIcon(new  javax.swing.ImageIcon( "H:\\4.png"));
        }
        if (tenshours == 5) {
            showOneHours.setIcon(new  javax.swing.ImageIcon( "H:\\5.png"));
        }
        if (tenshours == 6) {
            showOneHours.setIcon(new  javax.swing.ImageIcon( "H:\\6.png"));
        }
        if (tenshours == 7) {
            showOneHours.setIcon(new  javax.swing.ImageIcon( "H:\\7.png"));
        }
        if (tenshours == 8) {
            showOneHours.setIcon(new  javax.swing.ImageIcon( "H:\\8.png"));
        }
        if (tenshours == 9) {
            showOneHours.setIcon(new  javax.swing.ImageIcon( "H:\\9.png"));
        }

        String gg = Integer.toString(tenshours);
        tenHours.setText(gg);

        String ff = Integer.toString(hour);
        hours.setText (ff);

        String ee = Integer.toString(tensmins);
        tenMins.setText(ee);

        String aa = Integer.toString(secs);
        oneSecs.setText(aa);

        String bb = Integer.toString(ten);
        tenSecs.setText(bb);

        String cc = Integer.toString(min);
        minutes.setText(cc);

        String ss = Integer.toString(dd);
        digitValue.setText(ss);
          
        showDigitActionPerformed(evt);
    }//GEN-LAST:event_AddOneActionPerformed

    private void startTimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startTimerActionPerformed
        javax.swing.Timer tm = new javax.swing.Timer(100, new ActionListener()
            {
                public void actionPerformed (ActionEvent evt) {
                    
                    AddOneActionPerformed (evt);
                    
                    int ss11 = Integer.parseInt(oneSecs.getText());
                    int tt11 = Integer.parseInt(sec1.getText());
                    
                    int mm11 = Integer.parseInt(tenSecs.getText());
                    int yy11 = Integer.parseInt(tensec1.getText());
                    
                    int hh11 = Integer.parseInt(minutes.getText());
                    int aa11 = Integer.parseInt(min1.getText());
                    
                    int qq11 = Integer.parseInt(tenMins.getText());
                    int gg11 = Integer.parseInt(tenmin1.getText());
                    
                    int uu11 = Integer.parseInt(hours.getText());
                    int oo11 = Integer.parseInt(hour1.getText());
                    
                    int rr11 = Integer.parseInt(tenHours.getText());
                    int ww11 = Integer.parseInt(tenhour1.getText());
                    
                    
                    
                    // is the stop button pressed 
                    if (stopped == true) 
                    if (ss11 == tt11 && mm11 == yy11 && hh11 == aa11 && qq11 == gg11 && rr11 == ww11) {
                    stopped = false;
                    stopActionPerformed(evt);
                    
                    }
                    
                
                }
            });
            tm.start();
            
            
            
                    
                    
    }//GEN-LAST:event_startTimerActionPerformed

    private void sec1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sec1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sec1ActionPerformed

    private void showOneHoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showOneHoursActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showOneHoursActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    

        Date time = new Date();
        
        int ss = Integer.parseInt(oneSecs.getText());
        int mm = Integer.parseInt(minutes.getText());
        int hh = Integer.parseInt(hours.getText());
        
        
        DateFormat dateFormat = new SimpleDateFormat ("ss");   
        
        DateFormat dateFormat1 = new SimpleDateFormat ("mm");
        
        DateFormat dateFormat12 = new SimpleDateFormat ("HH");


        String S = dateFormat.format(time);
        String M = dateFormat1.format(time);
        String H = dateFormat12.format(time);       
        
        char ss1 = S.charAt(0);
        char ss2 = S.charAt(1);
        
        char mm1 = M.charAt(0);
        char mm2 = M.charAt(1);
        
        char hh1 = H.charAt(0);
        char hh2 = H.charAt(1);
        
       oneSecs.setText(Character.toString(ss2));
       
       AddOneActionPerformed (evt);

       
       tenSecs.setText(Character.toString(ss1));

        
       minutes.setText(Character.toString(mm2));
       
       
       tenMins.setText(Character.toString(mm1));
       
        
       hours.setText(Character.toString(hh2));
              
       
       tenHours.setText(Character.toString(hh1));
       
        AddOneActionPerformed (evt);
      dateFormat.format(time);

       
    
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void EndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EndActionPerformed
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_EndActionPerformed

    private void showHoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showHoursActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showHoursActionPerformed

    private void stopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopActionPerformed
oneSecs.setText("");
tenSecs.setText("");
minutes.setText("");
tenMins.setText("");
hours.setText("");
tenHours.setText("");
    }//GEN-LAST:event_stopActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
oneSecs.setText("00");
tenSecs.setText("00");
minutes.setText("00");
tenMins.setText("00");
hours.setText("00");
tenHours.setText("00");
    }//GEN-LAST:event_resetActionPerformed

    private void showOneSecsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showOneSecsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showOneSecsActionPerformed

    private void showMinsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showMinsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showMinsActionPerformed

    private void oneSecsDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneSecsDisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oneSecsDisplayActionPerformed

    private void oneSecsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneSecsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oneSecsActionPerformed

    private void hour1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hour1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hour1ActionPerformed

    private void min1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_min1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_min1ActionPerformed

    private void tenhour1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tenhour1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tenhour1ActionPerformed

    private void tenmin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tenmin1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tenmin1ActionPerformed

    private void tensec1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tensec1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tensec1ActionPerformed
  boolean stopped = false; 
//global
    private void StoptimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StoptimerActionPerformed
  
        stopped = true;
       
    }//GEN-LAST:event_StoptimerActionPerformed

    private void tenSecsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tenSecsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tenSecsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(timeeeee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(timeeeee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(timeeeee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(timeeeee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new timeeeee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddOne;
    private javax.swing.JButton End;
    private javax.swing.JButton Stoptimer;
    private javax.swing.JTextField digitValue;
    private javax.swing.JTextField hour1;
    private javax.swing.JTextField hours;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField min1;
    private javax.swing.JTextField minutes;
    private javax.swing.JTextField oneSecs;
    private javax.swing.JButton oneSecsDisplay;
    private javax.swing.JButton reset;
    private javax.swing.JTextField sec1;
    private javax.swing.JButton showDigit;
    private javax.swing.JButton showHours;
    private javax.swing.JButton showMins;
    private javax.swing.JButton showOneHours;
    private javax.swing.JButton showOneMins;
    private javax.swing.JButton showOneSecs;
    private javax.swing.JButton startTimer;
    private javax.swing.JButton stop;
    private javax.swing.JTextField tenHours;
    private javax.swing.JTextField tenMins;
    private javax.swing.JTextField tenSecs;
    private javax.swing.JTextField tenhour1;
    private javax.swing.JTextField tenmin1;
    private javax.swing.JTextField tensec1;
    // End of variables declaration//GEN-END:variables
}

